CREATE DATABASE QLKS
USE QLKS

CREATE TABLE PHONG(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaPhong CHAR(4) PRIMARY KEY NOT NULL,
	TenPhong NVARCHAR(10) NOT NULL, 
	MaLoaiP CHAR(2) NOT NULL,
	TinhTrang NVARCHAR(10) NOT NULL,
	DonGia MONEY NOT NULL,
	GhiChu NVARCHAR(100)
)

CREATE TABLE LOAIPHONG(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaLoaiP CHAR(2) PRIMARY KEY NOT NULL,
	TenLoaiP VARCHAR(10),
	GhiChu NVARCHAR(100)
)

CREATE TABLE KHACHHANG(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaKH CHAR(5) PRIMARY KEY NOT NULL,
	MaLoaiKH CHAR(2) NOT NULL,
	QuocTich NVARCHAR(20),
	SDT VARCHAR(11),
	EMAIL VARCHAR(30),
	CMND VARCHAR(10),
	DiaChi NVARCHAR(100)
)

CREATE TABLE LOAIKH(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaLoaiKH CHAR(2) PRIMARY KEY NOT NULL,
	TenLoaiKH NVARCHAR(10),
	GhiChu NVARCHAR(100)
)

CREATE TABLE NHANVIEN(
	MaNV CHAR(4) PRIMARY KEY NOT NULL,
	TenNV NVARCHAR(30),
	MaChucVu CHAR(3),
	GioiTinh NVARCHAR(3),
	CMND VARCHAR(10),
	SDT VARCHAR(11),
	DiaChi NVARCHAR(100),
	GhiChu NVARCHAR(100)
)

CREATE TABLE CHUCVU(
	MaChucVu CHAR(3) PRIMARY KEY NOT NULL,
	TenChucVu NVARCHAR(10),
	GhiChu NVARCHAR(100)
)

CREATE TABLE DICHVU(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaDV CHAR(5) PRIMARY KEY NOT NULL,
	MaLoaiDV CHAR(3) NOT NULL,
	DonGia MONEY NOT NULL,
	GhiChu NVARCHAR(100)
)

CREATE TABLE LOAIDV(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaLoaiDV CHAR(3) PRIMARY KEY NOT NULL,
	TenLoaiDV NVARCHAR(20),
	GhiChu NVARCHAR(100)
)

CREATE TABLE PHIEUTHUEPHONG(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaPhieuThue CHAR(3) PRIMARY KEY NOT NULL,
	MaPhong CHAR(4) NOT NULL,
	MaKH CHAR(5) NOT NULL,
	SoLuongKH tinyint,  
	MaNV CHAR(4) NOT NULL,
	NgayBDThue SMALLDATETIME NOT NULL,
	GhiChu NVARCHAR(100)
)

CREATE TABLE HOADON(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaHD CHAR(4) PRIMARY KEY NOT NULL,
	MaPhieuThue CHAR(3) NOT NULL,
	NgayKTThue SMALLDATETIME NOT NULL,
	SoNgayThue SMALLINT NOT NULL,
	TriGia MONEY NOT NULL,
	GhiChu NVARCHAR(100)
)

CREATE TABLE CTHD_DV(
	MaHD CHAR(4)NOT NULL,
	MaDV CHAR(5) NOT NULL,
	SoLuong TINYINT NOT NULL,
	ThanhTien MONEY NOT NULL,
	PRIMARY KEY(MaHD, MaDV)
)

CREATE TABLE BCDOANHTHU(
	Stt INT IDENTITY(1,1) NOT NULL,
	MaBC CHAR(4) PRIMARY KEY NOT NULL,
	MaHD CHAR(4),
	DoanhThu MONEY,
	TiLe FLOAT
 )

 ALTER TABLE PHONG			ADD CONSTRAINT FK_PHONG_LOAIPHONG	FOREIGN KEY(MaLoaiP)	REFERENCES LOAIPHONG(MaLoaiP)
 
 ALTER TABLE KHACHHANG		ADD CONSTRAINT FK_KHACHHANG_LOAIKH	FOREIGN KEY(MaLoaiKH)	REFERENCES LOAIKH(MaLoaiKH)
	
 ALTER TABLE NHANVIEN		ADD CONSTRAINT FK_NHANVIEN_CHUCVU	FOREIGN KEY(MaChucVu)	REFERENCES CHUCVU(MaChucVu)

 ALTER TABLE DICHVU			ADD CONSTRAINT FK_DICHVU_LOAIDV		FOREIGN KEY(MaLoaiDV)	REFERENCES LoaiDV(MaLoaiDV)
 
 ALTER TABLE PHIEUTHUEPHONG	ADD CONSTRAINT FK_PTHUEP_PHONG		FOREIGN KEY(MaPhong)	REFERENCES PHONG(MaPhong)
 
 ALTER TABLE PHIEUTHUEPHONG	ADD CONSTRAINT FK_PTHUEP_KHACHHANG	FOREIGN KEY(MAKH)		REFERENCES KHACHHANG(MAKH)
 
 ALTER TABLE PHIEUTHUEPHONG	ADD CONSTRAINT FK_PTHUEP_NHANVIEN	FOREIGN KEY(MaNV)		REFERENCES NHANVIEN(MaNV)
	
 ALTER TABLE HOADON			ADD CONSTRAINT FK_HOADON_PTHUEP		FOREIGN KEY(MaPhieuThue)REFERENCES PHIEUTHUEPHONG(MaPhieuThue)

 ALTER TABLE CTHD_DV		ADD CONSTRAINT FK_HDDV_HOADON		FOREIGN KEY(MaHD)		REFERENCES HOADON(MaHD)

 ALTER TABLE CTHD_DV		ADD CONSTRAINT FK_HDDV_DV			FOREIGN KEY(MaDV)		REFERENCES DICHVU(MaDV)

	


SET DATEFORMAT DMY